//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjectLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserRegisterMaster
    {
        public string UserId { get; set; }
        public string ResidentId { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public string LoginId { get; set; }
        public string Password { get; set; }
    
        public virtual tbl_ResidentMaster tbl_ResidentMaster { get; set; }
    }
}
